- name: copy toml file to /etc/gitlab-runner 
  copy:
    src: pod.yml
    dest: "/home/vagrant/pod.yml"
    #checksum: {{ checksum }}
    owner: root
    group: sudo
    mode: '0644'

- name: add gitlab-runner
  user:
    name: "{{ runner_user }}"
    comment: "Gitlab runner user"
    shell: /bin/bash
    create_home: yes
    append: yes

- name: install gitlab-runner
  shell: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
